#! /bin/bash
python /opt/project/pypyjs-release/pypyjs-release/tools/module_bundler.py add /opt/project/pypyjs-release/pypyjs-release/lib/modules/ /opt/project/cavorite/cavorite/
python3 /opt/project/binarycrate/manage.py $*

