# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryEdge',
            fields=[
                ('documentcollectionid', models.UUIDField()),
                ('documentid', models.CharField(max_length=250)),
                ('documentclassname', models.CharField(max_length=250)),
                ('classname', models.CharField(max_length=250)),
                ('endnodeid', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('startnode1id', models.CharField(max_length=250)),
                ('startnode2id', models.CharField(max_length=250)),
                ('propertyownerid', models.CharField(max_length=250)),
                ('propertyname', models.CharField(max_length=250)),
                ('propertyvalue', models.CharField(max_length=250)),
                ('propertytype', models.CharField(max_length=250)),
            ],
        ),
    ]
