# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-04 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historygraphbackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyedge',
            name='startnode2id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
