# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-31 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historygraphbackend', '0002_auto_20180304_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyedge',
            name='nonce',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='historyedge',
            name='classname',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='historyedge',
            name='documentclassname',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='historyedge',
            name='documentid',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='historyedge',
            name='propertyname',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='historyedge',
            name='propertyownerid',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='historyedge',
            name='propertytype',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='historyedge',
            name='propertyvalue',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='historyedge',
            name='startnode1id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
