# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-09 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historygraphbackend', '0003_auto_20180331_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='historyedge',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
