# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-25 04:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0003_blogindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='length',
            field=models.IntegerField(default=0, help_text='How long the lab will take to complete, in hours'),
        ),
    ]
