# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-14 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_directoryentry_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.IntegerField(choices=[(b'python', 0), (b'htmlcss', 1)]),
        ),
    ]
