# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-26 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180514_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.IntegerField(choices=[(0, b'python'), (1, b'webpage')]),
        ),
    ]
