# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-26 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180526_0729'),
        ('project', '0003_image'),
    ]

    operations = [
    ]
