# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-17 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20180517_0529'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='HomePage',
        ),
    ]
